### ISSUE TITLE
macos 上可以用这个插件吗？为啥我点击set config 无反应

### ISSUE THREAD

**Issue by gniqizeuy** [taosdata/vscode-tdengine#7]
点击 config 显示：command 'extension-to-3-0.login' not found
点击 refresh 显示: command 'nodeDependencies.refreshEntry' not found

**Comment by wjsvec** [comment]
嗯嗯目前还有一些小问题，应该是npm 的问题，会在后续版本中优化一下

**Comment by reboter** [comment]
It still doesn't work!
